#!/bin/bash

IP=$[RANDOM%256].$[RANDOM%256].$[RANDOM%256].$[RANDOM%256]
echo -e "HELO\t2"
echo -e "Q	www.spacephone.org	IN	ANY	-1	$IP	0.0.0.0"
echo -e "Q	spacephone.org	IN	ANY	-1	$IP	0.0.0.0"
echo -e "Q	1.1.1.f.3.8.e.f.f.f.e.3.6.1.2.0.0.4.0.0.0.1.5.d.0.7.4.0.1.0.0.2.ip6.arpa	IN	PTR	-1	$IP	0.0.0.0"
echo -e "Q	1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.2.4.0.0.0.1.5.d.0.7.4.0.1.0.0.2.ip6.arpa	IN	PTR	-1	$IP	0.0.0.0"
echo -e "Q	69.42.23.172.in-addr.arpa	IN	PTR	-1	$IP	0.0.0.0"
echo -e "Q	node-08b3tvvugfoh2-6.pub.auto.maze.so	IN	AAAA	-1	$IP	0.0.0.0"
echo -e "Q	node-xensource-00-16-3e-83-f1-11-6.pub.auto.maze.so	IN	AAAA	-1	$IP	0.0.0.0"
echo -e "Q	node-04-6.lab.auto.maze.so	IN	A	-1	$IP	0.0.0.0"
echo -e "Q	node-04-6.lab.auto.maze.so	IN	AAAA	-1	$IP	0.0.0.0"
echo -e "Q	node-8k-4.lab.auto.maze.so	IN	A	-1	$IP	0.0.0.0"
echo -e "Q	node-8k-4.lab.auto.maze.so	IN	ANY	-1	$IP	0.0.0.0"
